name: C++ CI Workflow with apt dependencies

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'

jobs:
  build:
    name: '[${{ matrix.docker_image }}@${{ matrix.build_type }}@apt]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Release]
        os:
          - ubuntu-latest
        docker_image:
          - "ubuntu:20.04"
          - "ubuntu:22.04"
          - "debian:sid"      
    container:
      image: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v3


    - name: Dependencies
      run: |
        apt-get update
        apt-get -y upgrade
        apt-get -y install cmake pkg-config build-essential ninja-build libssl-dev libuv1-dev libz-dev libboost-dev

    - name: Configure
      run: |
        mkdir -p build
        cd build
        cmake -GNinja -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ..

    - name: Build
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      shell: bash -l {0}
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}

